ifneq ($(KBUILD_EXTMOD),)

EXTRA_CFLAGS += \
	-I$(TOPDIR)/include \
	-I$(TOPDIR)/drivers/net/can/hal \
	\
	-DETH_P_CAN=0x000C \
	-DARPHRD_CAN=280 \
	-DPF_CAN=29 \
	-DAF_CAN=PF_CAN \
	\
	-DCONFIG_CAN_RAW_USER \
	-DCONFIG_CAN_BCM_USER

endif
