ifneq ($(KBUILD_EXTMOD),)

EXTRA_CFLAGS += \
	-I$(TOPDIR)/include \
	-I$(TOPDIR)/drivers/net/can/hal \
	\
	-DETH_P_CAN=0x000C \
	-DARPHRD_CAN=280 \
	-DCONFIG_CAN_DEBUG_CORE \
	-DPF_CAN=29 \
	-DAF_CAN=PF_CAN

endif
